Repository googleapis/python-spanner, pull requests merged in 2020-05, with the labels that each got.

#66 feat: add support for retrying aborted partitioned DML statements
  google/cloud/spanner_v1/database.py
  tests/unit/test_database.py
Labels: cla: yes

#75 refactor: PingingPool pings sessions using SELECT 1
  google/cloud/spanner_v1/pool.py
  google/cloud/spanner_v1/session.py
  tests/unit/test_pool.py
  tests/unit/test_session.py
Labels: automerge, cla: yes

#69 tests: add backup integration tests
  tests/system/test_system.py
Labels: cla: yes

#80 test: remove unneeded system test skip when using emulator
  tests/system/test_system.py
Labels: cla: yes

#82 fix: update backup timeouts (via synth)
  .kokoro/publish-docs.sh
  google/cloud/spanner_admin_database_v1/gapic/database_admin_client.py
  google/cloud/spanner_admin_database_v1/gapic/database_admin_client_config.py
  google/cloud/spanner_admin_database_v1/gapic/enums.py
  google/cloud/spanner_admin_database_v1/gapic/transports/database_admin_grpc_transport.py
  google/cloud/spanner_admin_instance_v1/gapic/enums.py
  google/cloud/spanner_admin_instance_v1/gapic/instance_admin_client.py
  google/cloud/spanner_admin_instance_v1/gapic/transports/instance_admin_grpc_transport.py
  google/cloud/spanner_v1/gapic/enums.py
  google/cloud/spanner_v1/gapic/spanner_client.py
  google/cloud/spanner_v1/gapic/transports/spanner_grpc_transport.py
  synth.metadata
Labels: cla: yes

#81 test: fix result ordering errors for emulator
  tests/system/test_system.py
Labels: api: spanner, cla: yes

#87 feat: add support for using the emulator programatically
  google/cloud/spanner_v1/client.py
  google/cloud/spanner_v1/database.py
  tests/unit/test_client.py
Labels: cla: yes
