Repository googleapis/python-spanner, pull requests merged in 2020-08, with the labels that each got.

#124 test: fix failing unit test on master
  tests/unit/test_client.py
Labels: api: spanner, cla: yes

#126 chore: add missing ci files; update UpdateBackup retry params (via synth)
  .gitignore
  .kokoro/build.sh
  .kokoro/docker/docs/Dockerfile
  .kokoro/docker/docs/fetch_gpg_keys.sh
  .kokoro/docs/common.cfg
  .kokoro/docs/docs-presubmit.cfg
  .kokoro/publish-docs.sh
  .kokoro/trampoline_v2.sh
  .trampolinerc
  docs/conf.py
  google/cloud/spanner_admin_database_v1/gapic/database_admin_client_config.py
  noxfile.py
  synth.metadata
Labels: automerge, cla: yes, context: partial

#127 docs: add install reference for cloud trace exporter (opentelemetry)
  docs/opentelemetry-tracing.rst
Labels: automerge, cla: yes

#132 feat(spanner): add client_options to base class
  google/cloud/spanner_v1/client.py
  setup.py
  tests/unit/test_client.py
Labels: cla: yes

#133 build: pin opentelemetry dependencies
  noxfile.py
  setup.py
Labels: automerge, cla: yes

#134 build: ensure tracing dependencies are installed for tests
  noxfile.py
Labels: api: spanner, cla: yes

#136 docs: add instructions for using a Cloud Spanner emulator
  docs/client-usage.rst
Labels: api: spanner, cla: yes

#122 fix: resume iterator on EOS internal error
  google/cloud/spanner_v1/snapshot.py
  tests/unit/test_snapshot.py
Labels: api: spanner, cla: yes
