Repository googleapis/python-spanner, pull requests merged in 2020-09, with the labels that each got.

#138 fix: Remove stray bigquery lines in .gitignore, build script
  .gitignore
  test_utils/scripts/update_docs.sh
Labels: api: spanner, cla: yes

#86 feat: add support for NUMERIC type
  google/cloud/spanner_v1/_helpers.py
  google/cloud/spanner_v1/param_types.py
  tests/_fixtures.py
  tests/system/test_system.py
  tests/unit/test__helpers.py
Labels: api: spanner, cla: yes

#143 fix: update list_instances() to use the filter_ arg
  google/cloud/spanner_v1/client.py
  tests/unit/test_client.py
Labels: cla: yes

#146 docs: update samples from python-docs-samples
  samples/samples/README.rst
  samples/samples/backup_sample.py
  samples/samples/backup_sample_test.py
  samples/samples/requirements-test.txt
  samples/samples/snippets.py
  samples/samples/snippets_test.py
Labels: automerge, cla: yes
