Repository googleapis/python-spanner, pull requests merged in 2020-07, with the labels that each got.

#109 docs: tiny typo fix
  google/cloud/spanner_v1/snapshot.py
Labels: api: spanner, cla: yes, type: docs

#113 refactor: remove unused _count attribute from StreamedResultSet class
  google/cloud/spanner_v1/streamed.py
Labels: api: spanner, cla: yes, type: cleanup

#114 ci: add GitHub action for emulator system tests
  .github/workflows/integration-tests-against-emulator.yaml
Labels: api: spanner, automerge, cla: yes

#101 chore: use new grpc version; update templates; update retry/timeout configs; add NUMERIC type
  .kokoro/samples/lint/common.cfg
  .kokoro/samples/lint/continuous.cfg
  .kokoro/samples/lint/periodic.cfg
  .kokoro/samples/lint/presubmit.cfg
  .kokoro/samples/python3.6/common.cfg
  .kokoro/samples/python3.6/continuous.cfg
  .kokoro/samples/python3.6/periodic.cfg
  .kokoro/samples/python3.6/presubmit.cfg
  .kokoro/samples/python3.7/common.cfg
  .kokoro/samples/python3.7/continuous.cfg
  .kokoro/samples/python3.7/periodic.cfg
  .kokoro/samples/python3.7/presubmit.cfg
  .kokoro/samples/python3.8/common.cfg
  .kokoro/samples/python3.8/continuous.cfg
  .kokoro/samples/python3.8/periodic.cfg
  .kokoro/samples/python3.8/presubmit.cfg
  .kokoro/test-samples.sh
  google/cloud/spanner_admin_database_v1/gapic/database_admin_client.py
  google/cloud/spanner_admin_database_v1/gapic/database_admin_client_config.py
  google/cloud/spanner_admin_database_v1/gapic/transports/database_admin_grpc_transport.py
  google/cloud/spanner_admin_database_v1/proto/backup_pb2_grpc.py
  google/cloud/spanner_admin_database_v1/proto/common_pb2_grpc.py
  google/cloud/spanner_admin_database_v1/proto/spanner_database_admin.proto
  google/cloud/spanner_admin_database_v1/proto/spanner_database_admin_pb2.py
  google/cloud/spanner_admin_database_v1/proto/spanner_database_admin_pb2_grpc.py
  google/cloud/spanner_admin_instance_v1/gapic/instance_admin_client.py
  google/cloud/spanner_admin_instance_v1/gapic/instance_admin_client_config.py
  google/cloud/spanner_admin_instance_v1/gapic/transports/instance_admin_grpc_transport.py
  google/cloud/spanner_admin_instance_v1/proto/spanner_instance_admin_pb2.py
  google/cloud/spanner_admin_instance_v1/proto/spanner_instance_admin_pb2_grpc.py
  google/cloud/spanner_v1/gapic/enums.py
  google/cloud/spanner_v1/gapic/spanner_client_config.py
  google/cloud/spanner_v1/proto/keys_pb2.py
  google/cloud/spanner_v1/proto/keys_pb2_grpc.py
  google/cloud/spanner_v1/proto/mutation_pb2_grpc.py
  google/cloud/spanner_v1/proto/query_plan_pb2_grpc.py
  google/cloud/spanner_v1/proto/result_set_pb2_grpc.py
  google/cloud/spanner_v1/proto/spanner_pb2.py
  google/cloud/spanner_v1/proto/spanner_pb2_grpc.py
  google/cloud/spanner_v1/proto/transaction_pb2_grpc.py
  google/cloud/spanner_v1/proto/type.proto
  google/cloud/spanner_v1/proto/type_pb2.py
  google/cloud/spanner_v1/proto/type_pb2_grpc.py
  scripts/decrypt-secrets.sh
  scripts/readme-gen/readme_gen.py
  scripts/readme-gen/templates/README.tmpl.rst
  scripts/readme-gen/templates/auth.tmpl.rst
  scripts/readme-gen/templates/auth_api_key.tmpl.rst
  scripts/readme-gen/templates/install_deps.tmpl.rst
  scripts/readme-gen/templates/install_portaudio.tmpl.rst
  synth.metadata
  testing/.gitignore
  tests/unit/gapic/v1/test_database_admin_client_v1.py
  tests/unit/gapic/v1/test_instance_admin_client_v1.py
Labels: automerge, cla: yes, context: none

#107 feat: add OpenTelemetry tracing to spanner calls
  docs/index.rst
  docs/opentelemetry-tracing.rst
  google/cloud/spanner_v1/_opentelemetry_tracing.py
  google/cloud/spanner_v1/batch.py
  google/cloud/spanner_v1/session.py
  google/cloud/spanner_v1/snapshot.py
  google/cloud/spanner_v1/transaction.py
  noxfile.py
  tests/_helpers.py
  tests/system/test_system.py
  tests/unit/test__opentelemetry_tracing.py
  tests/unit/test_batch.py
  tests/unit/test_session.py
  tests/unit/test_snapshot.py
  tests/unit/test_transaction.py
Labels: cla: yes

#117 docs: add samples from spanner/cloud-client
  .github/CODEOWNERS
  docs/_templates/layout.html
  samples/AUTHORING_GUIDE.md
  samples/CONTRIBUTING.md
  samples/samples/README.rst
  samples/samples/README.rst.in
  samples/samples/backup_sample.py
  samples/samples/backup_sample_test.py
  samples/samples/batch_sample.py
  samples/samples/noxfile.py
  samples/samples/quickstart.py
  samples/samples/quickstart_test.py
  samples/samples/requirements-test.txt
  samples/samples/requirements.txt
  samples/samples/snippets.py
  samples/samples/snippets_test.py
  synth.metadata
  synth.py
Labels: cla: yes
