Repository googleapis/python-spanner, pull requests merged in 2020-03, with the labels that each got.

#29 docs: correct URLs for old issues
  CHANGELOG.md
Labels: cla: yes, type: docs

#27 chore: add query options (via synth)
  google/cloud/spanner_admin_database_v1/proto/spanner_database_admin.proto
  google/cloud/spanner_admin_database_v1/proto/spanner_database_admin_pb2_grpc.py
  google/cloud/spanner_admin_instance_v1/gapic/instance_admin_client.py
  google/cloud/spanner_admin_instance_v1/proto/spanner_instance_admin.proto
  google/cloud/spanner_admin_instance_v1/proto/spanner_instance_admin_pb2.py
  google/cloud/spanner_v1/gapic/spanner_client.py
  google/cloud/spanner_v1/gapic/transports/spanner_grpc_transport.py
  google/cloud/spanner_v1/proto/keys.proto
  google/cloud/spanner_v1/proto/mutation.proto
  google/cloud/spanner_v1/proto/mutation_pb2.py
  google/cloud/spanner_v1/proto/query_plan.proto
  google/cloud/spanner_v1/proto/result_set.proto
  google/cloud/spanner_v1/proto/spanner.proto
  google/cloud/spanner_v1/proto/spanner_pb2.py
  google/cloud/spanner_v1/proto/spanner_pb2_grpc.py
  google/cloud/spanner_v1/proto/transaction.proto
  google/cloud/spanner_v1/proto/type.proto
  synth.metadata
Labels: cla: yes

#30 feat: implement query options versioning support
  google/cloud/spanner_v1/_helpers.py
  google/cloud/spanner_v1/client.py
  google/cloud/spanner_v1/database.py
  google/cloud/spanner_v1/session.py
  google/cloud/spanner_v1/snapshot.py
  google/cloud/spanner_v1/transaction.py
  tests/unit/test__helpers.py
  tests/unit/test_client.py
  tests/unit/test_database.py
  tests/unit/test_session.py
  tests/unit/test_snapshot.py
  tests/unit/test_transaction.py
Labels: api: spanner, cla: yes

#31 chore: add backups (via synth)
  google/cloud/spanner_admin_database_v1/gapic/database_admin_client.py
  google/cloud/spanner_admin_database_v1/gapic/database_admin_client_config.py
  google/cloud/spanner_admin_database_v1/gapic/enums.py
  google/cloud/spanner_admin_database_v1/gapic/transports/database_admin_grpc_transport.py
  google/cloud/spanner_admin_database_v1/proto/backup.proto
  google/cloud/spanner_admin_database_v1/proto/backup_pb2.py
  google/cloud/spanner_admin_database_v1/proto/backup_pb2_grpc.py
  google/cloud/spanner_admin_database_v1/proto/common.proto
  google/cloud/spanner_admin_database_v1/proto/common_pb2.py
  google/cloud/spanner_admin_database_v1/proto/common_pb2_grpc.py
  google/cloud/spanner_admin_database_v1/proto/spanner_database_admin.proto
  google/cloud/spanner_admin_database_v1/proto/spanner_database_admin_pb2.py
  google/cloud/spanner_admin_database_v1/proto/spanner_database_admin_pb2_grpc.py
  google/cloud/spanner_admin_instance_v1/proto/spanner_instance_admin_pb2.py
  synth.metadata
  tests/unit/gapic/v1/test_database_admin_client_v1.py
Labels: cla: yes

#35 feat: add support for backups
  google/cloud/spanner_v1/backup.py
  google/cloud/spanner_v1/database.py
  google/cloud/spanner_v1/instance.py
  tests/unit/test_backup.py
  tests/unit/test_database.py
  tests/unit/test_instance.py
Labels: api: spanner, cla: yes

#44 docs: Add documentation for using DML statements in a transaction
  docs/transaction-usage.rst
Labels: cla: yes

#19 fix: increment seqno before execute calls to prevent InvalidArgument …
  google/cloud/spanner_v1/transaction.py
  tests/unit/test_snapshot.py
  tests/unit/test_transaction.py
Labels: cla: yes

#43 docs: Fix incorrect generated return types
  synth.py
Labels: cla: yes
