Repository googleapis/python-spanner, pull requests merged in 2020-04, with the labels that each got.

#51 fix: Pin Sphnix version to last working release
  noxfile.py
Labels: cla: yes

#49 fix: add keepalive to gRPC channel
  google/cloud/spanner_v1/gapic/transports/spanner_grpc_transport.py
Labels: cla: yes

#46 chore: Update incorrect type (via synth)
  google/cloud/spanner_admin_database_v1/gapic/database_admin_client.py
  google/cloud/spanner_admin_database_v1/proto/common_pb2.py
  google/cloud/spanner_admin_instance_v1/gapic/instance_admin_client.py
  google/cloud/spanner_v1/proto/query_plan_pb2.py
  synth.metadata
Labels: cla: yes

#54 docs(spanner): changes to support sphinx new release
  CHANGELOG.md
  docs/conf.py
  docs/gapic/v1/admin_database_types.rst
  docs/gapic/v1/admin_instance_types.rst
  docs/gapic/v1/types.rst
  noxfile.py
Labels: cla: yes

#55 fix: add keepalive changes to synth.py
  synth.py
Labels: cla: yes, release blocking

#48 docs(spanner): fix single character parameter
  google/cloud/spanner_v1/client.py
  google/cloud/spanner_v1/database.py
  google/cloud/spanner_v1/instance.py
  google/cloud/spanner_v1/session.py
  google/cloud/spanner_v1/snapshot.py
  google/cloud/spanner_v1/streamed.py
  google/cloud/spanner_v1/transaction.py
Labels: cla: yes

#26 fix: pass gRPC config options to gRPC channel creation
  google/cloud/spanner_v1/gapic/transports/spanner_grpc_transport.py
  synth.py
Labels: cla: yes

#57 test: use assertIsInstance where possible
  tests/unit/test_backup.py
  tests/unit/test_client.py
  tests/unit/test_database.py
  tests/unit/test_instance.py
Labels: cla: yes

#62 docs: update how to set up background thread to ping PingingPool and …
  docs/advanced-session-pool-topics.rst
Labels: cla: yes

#63 docs: add begin_pending_transactions() to the background thread examp…
  docs/advanced-session-pool-topics.rst
Labels: cla: yes

#59 docs: make it clear ddl_statements is a list in docs
  docs/database-usage.rst
Labels: cla: yes

#64 chore: Migrate python-spanner synth.py from artman to bazel
  synth.py
Labels: automerge, cla: yes

#70 docs: re-pin sphinx version
  CHANGELOG.md
  docs/conf.py
  noxfile.py
Labels: automerge, cla: yes

#65 chore: update backup timeout config (via synth)
  .coveragerc
  .flake8
  .github/ISSUE_TEMPLATE/bug_report.md
  CONTRIBUTING.rst
  MANIFEST.in
  google/cloud/spanner_admin_database_v1/gapic/database_admin_client_config.py
  google/cloud/spanner_admin_database_v1/proto/backup.proto
  google/cloud/spanner_admin_database_v1/proto/backup_pb2.py
  setup.cfg
  synth.metadata
Labels: automerge, cla: yes

#73 refactor: remove deprecated resource based routing support
  google/cloud/spanner_v1/client.py
  google/cloud/spanner_v1/database.py
  tests/system/test_system.py
  tests/unit/test_database.py
Labels: cla: yes
