Repository googleapis/python-spanner, pull requests merged in 2021-12, with the labels that each got.

#648 chore: auto-assign issues to new repo owner
  .github/blunderbuss.yml
Labels: api: spanner, cla: yes, automerge

#640 chore: changing default region to us-west1
  samples/samples/backup_sample.py
  tests/system/conftest.py
  tests/system/test_backup_api.py
Labels: api: spanner, cla: yes

#655 chore: add api_shortname to repo-metadata.json
  .repo-metadata.json
Labels: api: spanner
